apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/created-by: lws-operator
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: lws-operator
    control-plane: controller-manager
  name: lws-controller-manager
  namespace: openshift-lws-system
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --config=/controller_manager_config.yaml
            - --zap-log-level=2
          command:
            # TODO: disable internal cert rotation, configure webhook certdir if necessary
            - /manager
          image: gcr.io/k8s-staging-lws/lws:main
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - name: lws-manager-config
              mountPath: /controller_manager_config.yaml
              subPath: controller_manager_config.yaml
      securityContext:
        runAsNonRoot: true
      serviceAccountName: lws-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: lws-webhook-server-cert
        - name: lws-manager-config
          configMap:
            name: lws-manager-config