apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lws
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: lws
  name: openshift-lws-leader-election-rolebinding
  namespace: openshift-lws-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-lws-leader-election-role
subjects:
  - kind: ServiceAccount
    name: openshift-lws-controller-manager
    namespace: openshift-lws-system