apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/created-by: lws-operator
    app.kubernetes.io/name: service
  name: openshift-lws-webhook-service
  namespace: openshift-lws-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager