apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lws-operator
    control-plane: controller-manager
  name: lws-controller-manager-metrics-service
  namespace: openshift-lws-system
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: controller-manager

