apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-lws-operator
  namespace: openshift-lws-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-lws-operator
  template:
    metadata:
      labels:
        name: openshift-lws-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: openshift-lws-operator
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          image: ${OPERATOR_IMAGE}
          volumeMounts:
            - name: tmp
              mountPath: "/tmp"
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - lws-operator
          args:
            - "operator"
          imagePullPolicy: Always
          env:
            - name: OPERATOR_NAME
              value: "openshift-lws-operator"
            - name: RELATED_IMAGE_OPERAND_IMAGE
              value: ${OPERAND_IMAGE}
      serviceAccountName: openshift-lws-operator
      volumes:
        - name: tmp
          emptyDir: {}
